*&---------------------------------------------------------------------*
*& Report Z_CLASSICALREP2
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT Z_CLASSICALREP2
NO STANDARD PAGE HEADING
LINE-SIZE 600
LINE-COUNT 20(3)
MESSAGE-ID Z_MESSAGECLASS.
*DECLARATION
TYPES: BEGIN OF TYPE1,
       KUNNR TYPE KNA1-KUNNR,
       NAME1 TYPE KNA1-NAME1,
       LAND1 TYPE KNA1-LAND1,
       ORT01 TYPE KNA1-ORT01,
       PSTLZ TYPE KNA1-PSTLZ,
       TELF1 TYPE KNA1-TELF1,
      END OF TYPE1.
DATA: ITAB TYPE TABLE OF TYPE1,
      WA TYPE TYPE1.
DATA: V1 TYPE KNA1-KUNNR.

*INPUTS

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE T1.
SELECT-OPTIONS CUSTOMER FOR V1 OBLIGATORY.
 SELECTION-SCREEN END OF BLOCK B1.
 INITIALIZATION.
T1 = 'CUSTOMER NUMBER CLASSICAL REPORT'.

*PROCESS

START-OF-SELECTION.
PERFORM SUBR_CS.

*PAGE HEADINGS.

TOP-OF-PAGE.
WRITE:/ 'DATE' COLOR 2 , SY-DATUM , 20 'TIME' COLOR 3, SY-TIMLO,
      45 'PAGE-NO' COLOR 4, SY-PAGNO.
WRITE:/25 'CUSTOMER NO' COLOR 4, CUSTOMER-LOW , 'TO', CUSTOMER-HIGH, 'ORDER LIST'.
SKIP.
ULINE.
WRITE:/5 'NAME' COLOR 4, 50 'COUNTRY' COLOR 4,
 65 'CITY' COLOR 4, 120 'POSTAL CODE' COLOR 4,
 140 'TELEPHONE' COLOR 3.
ULINE.


   END-OF-PAGE.
     ULINE AT /70(20).
     WRITE:/70 '|' , 75 'End of Page' COLOR 6 , 89 '|'.
     ULINE AT /70(20).

END-OF-SELECTION.

*OUTPUT
CASE SY-SUBRC.
  WHEN 0.
    PERFORM SUBR_OUTPUT.
  WHEN 4.
    MESSAGE E001.
  ENDCASE.
*SUBROUTINE FOR SELECT QUERY
FORM SUBR_CS .
SELECT KUNNR NAME1 LAND1
   ORT01 PSTLZ TELF1
  INTO TABLE ITAB FROM KNA1
  WHERE KUNNR IN CUSTOMER.
ENDFORM.
*SUBROUTINE FOR OUTPUT
FORM SUBR_OUTPUT .
SORT ITAB BY KUNNR.
LOOP AT ITAB INTO WA.
  AT NEW KUNNR.
    WRITE:/ 'CUSTOMER NO' COLOR 2, WA-KUNNR COLOR 3.
  ENDAT.
  WRITE:/5 WA-NAME1 COLOR 1,50 WA-LAND1 COLOR 2,
        65 WA-ORT01 COLOR 4, 120 WA-PSTLZ COLOR 6,
        140 WA-TELF1 COLOR 5.

  ENDLOOP.
ENDFORM.
