*
REPORT Z_DISPLAYT001.
 DATA: BEGIN OF ITAB,
       BUKRS TYPE T001-BUKRS,
       BUTXT TYPE T001-BUTXT,
       LAND1 TYPE T001-LAND1,
       WAERS TYPE T001-WAERS,
       END OF ITAB.


  PARAMETERS COMPANY TYPE T001-BUKRS OBLIGATORY.

    START-OF-SELECTION.
    SELECT BUKRS BUTXT LAND1 WAERS
    INTO ITAB FROM T001
    WHERE BUKRS EQ COMPANY.
       ENDSELECT.
    IF SY-SUBRC EQ 0.
      WRITE:/'ORG DATA INFO', 20 ITAB-BUKRS,
           /5'COMPANY CODE' , 20 ITAB-BUTXT,
           /5'COMPANY NAME',  20 ITAB-LAND1,
           /5'CURRRENCY KEY', 20 ITAB-WAERS.
      ELSE.
        MESSAGE 'COMPANY CODE NOT FOUND' TYPE 'S'.
        ENDIF.
