PROCESS BEFORE OUTPUT.
MODULE STATUS_0100.

  " Call subscreens inside main screen
  CALL SUBSCREEN SUBSCA1 INCLUDING 'Z_GLACCINFO' '0101'.
  CALL SUBSCREEN SUBSCA2 INCLUDING 'Z_GLACCINFO' '0102'.

PROCESS AFTER INPUT.
  CALL SUBSCREEN SUBSCA1.
  CALL SUBSCREEN SUBSCA2.
 MODULE USER_COMMAND_0100.
