*&---------------------------------------------------------------------*
*& Report Z_INTERACTIVEREPORT1
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT Z_INTERACTIVEREPORT1
NO STANDARD PAGE HEADING
MESSAGE-ID Z_MESSAGECLASS.
*declarations

TYPES: BEGIN OF TYPE1,
       EBELN TYPE EKKO-EBELN,
       BEDAT TYPE EKKO-BEDAT,
       BSART TYPE EKKO-BSART,
       STATU TYPE EKKO-STATU,
       BUKRS TYPE EKKO-BUKRS,
       END OF TYPE1,

       BEGIN OF TYPE2,
       EBELN TYPE EKPO-EBELN,
       EBELP TYPE EKPO-EBELP,
       MATNR TYPE EKPO-MATNR,
       END   OF TYPE2,

       BEGIN OF TYPE3,
         MATNR TYPE MARA-MATNR,
         MAKTG TYPE MAKT-MAKTG,
         MEINS TYPE MARA-MEINS,
         MTART TYPE MARA-MTART,
         MATKL TYPE MARA-MATKL,
       END   OF TYPE3.
 DATA: ITAB1 TYPE TABLE OF TYPE1,
       WA1   TYPE TYPE1,
       ITAB2 TYPE TABLE OF TYPE2,
       WA2   TYPE TYPE2,
       ITAB3 TYPE TABLE OF TYPE3,
       WA3   TYPE TYPE3.
*inputs
  INCLUDE: Z_INTERACTIVE1.
*process
  START-OF-SELECTION.
  PERFORM SUBR_OPENSQL.
  END-OF-SELECTION.
*outputs
  CASE SY-SUBRC.
    WHEN 0.
      PERFORM SUBR_OUTPUT1.
    WHEN 4.
      MESSAGE S004.
  ENDCASE.
*SUB ROUTINE FOR SELECT 1
FORM SUBR_OPENSQL .
SELECT  EBELN BEDAT BSART STATU BUKRS INTO TABLE ITAB1 FROM EKKO WHERE BEDAT IN PODATE.
ENDFORM.
*
FORM SUBR_OUTPUT1 .
 SORT ITAB1 BY EBELN.
 LOOP AT ITAB1 INTO WA1.
      AT FIRST.
       WRITE:/ 'PURCHASE ORDER DATA' COLOR 2.
      ENDAT.
      WRITE:/5 WA1-EBELN HOTSPOT COLOR 4, 20 WA1-BEDAT COLOR 3, 40 WA1-BSART COLOR 6, 65 WA1-STATU COLOR 7, 90 WA1-BUKRS COLOR 1.
      HIDE WA1-EBELN.
 ENDLOOP.
ENDFORM.
AT LINE-SELECTION.
  CASE SY-LSIND.
    WHEN 1.
      PERFORM SUBR_OPENSQL2 USING WA1-EBELN.
    IF SY-SUBRC EQ 0.
      PERFORM SUBR_OUTPUT2.
    ELSE.
      MESSAGE S004.
    ENDIF.
      WHEN 2.
      PERFORM SUBR_OPENSQL3 USING WA2-MATNR.
    IF SY-SUBRC EQ 0.
      PERFORM SUBR_OUTPUT3.
    ELSE.
      MESSAGE S005.
    ENDIF.
    ENDCASE.

*SUBROUTINE FOR 2ND OUTPUT.
    FORM SUBR_OPENSQL2  USING    P_WA1_EBELN.
SELECT EBELN EBELP MATNR INTO TABLE ITAB2 FROM EKPO WHERE EBELN EQ P_WA1_EBELN.
ENDFORM.
*SUBROUTINE FOR 2ND OUTPUT DISPLAY
FORM SUBR_OUTPUT2 .
SORT ITAB2 BY MATNR EBELN.
LOOP AT ITAB2 INTO WA2.
  AT FIRST.
    WRITE:/ 'PURCHASING DOCUMENT ITEM DATA' COLOR 4.
  ENDAT.
  WRITE:/5 WA2-EBELN COLOR 3, 20 WA2-EBELP COLOR 4, 40 WA2-MATNR HOTSPOT COLOR 5.
  HIDE WA2-MATNR.

  ENDLOOP.
ENDFORM.
*3RD OUTPUT SELECTION.
*3RD OUTPUT SELECT QUERY
FORM SUBR_OPENSQL3  USING    P_WA2_MATNR.
SELECT A~MATNR A~MEINS A~MTART A~MATKL
       B~MAKTG  INTO TABLE ITAB3 FROM
       MARA AS A INNER JOIN MAKT AS
       B ON A~MATNR = B~MATNR
        WHERE A~MATNR EQ P_WA2_MATNR
        AND B~SPRAS = SY-LANGU.
ENDFORM.
*OUTPUT 3 DISPLAY.
FORM SUBR_OUTPUT3 .
SORT ITAB3 BY MATNR.
LOOP AT ITAB3 INTO WA3.
  AT FIRST.
    WRITE:/ 'MATERIAL INFO FROM MARA AND MAKT' COLOR 2.
    ENDAT.
 WRITE:/5 WA3-MATNR COLOR 1, 20 WA3-MAKTG COLOR 2,
       40 WA3-MEINS COLOR 3, 65 WA3-MTART COLOR 4,
       90 WA3-MATKL COLOR 5.
       CLEAR WA3.

  ENDLOOP.
ENDFORM.
