*&---------------------------------------------------------------------*
*&  Include           Z_INCLUDE6
*&---------------------------------------------------------------------D
DATA V1 TYPE VBAK-ERDAT.
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE T1.
  PARAMETERS CUSTOMER TYPE KNA1-KUNNR.
SELECTION-SCREEN END OF BLOCK B1.
SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE T2.
  SELECT-OPTIONS DATE FOR V1.
SELECTION-SCREEN END OF BLOCK B2.
INITIALIZATION.
T1 = 'ENTER CUSTOMER NUMBER'.
T2 = 'ENTER DATE'.
