REPORT Z_INTERNALTABLE124.
TYPE-POOLS: Z2127.
DATA: ITAB TYPE HASHED  TABLE OF Z2127_ITEMTYPE WITH UNIQUE KEY ITEM,
      WA TYPE Z2127_ITEMTYPE.
*STORING
WA-ITEM = 'MOONGDAL'. WA-QUANT = 3. WA-URATE = 250.
INSERT WA INTO TABLE ITAB.
CLEAR WA.
WA-ITEM = 'TOORDAL'. WA-QUANT = 5. WA-URATE = 500.
INSERT WA INTO TABLE ITAB.
CLEAR WA.
WA-ITEM = 'CHANADAL'. WA-QUANT = 8. WA-URATE = 900.
INSERT WA INTO TABLE ITAB.
CLEAR WA.
WA-ITEM = 'MASHDAL'. WA-QUANT = 6. WA-URATE = 800.
INSERT WA INTO TABLE ITAB.
CLEAR WA.
WA-ITEM = 'MASHDAL'. WA-QUANT = 9. WA-URATE = 850.
INSERT WA INTO TABLE ITAB.
CLEAR WA.
*DISPLAY
LOOP AT ITAB INTO WA.
WRITE:/ WA-ITEM COLOR 4, WA-QUANT COLOR 5, WA-URATE COLOR 7.
ENDLOOP.
