
REPORT Z_OPENSQLP2.
DATA: BEGIN OF ITAB,
      MATNR TYPE MARA-MATNR,
      MTART TYPE MARA-MTART,
      MATKL TYPE MARA-MATKL,
      MEINS TYPE MARA-MEINS,
      END OF ITAB.

      DATA V1 TYPE MARA-MATNR.
      SELECT-OPTIONS VENDOR FOR V1 OBLIGATORY.

      START-OF-SELECTION.
      SELECT MATNR MTART MATKL MEINS INTO ITAB FROM MARA
        WHERE MATNR IN VENDOR.

        WRITE:/ ITAB-MATNR COLOR 3,25 ITAB-MTART COLOR 5,70 ITAB-MATKL COLOR 2, 90 ITAB-MEINS COLOR 6.
        ENDSELECT.
        IF SY-SUBRC EQ 0.
          MESSAGE 'DATA NOT FOUND' TYPE 'S'.
        ENDIF.
