
REPORT Z_OPENSQLP1.

DATA : BEGIN OF ITAB,
       LIFNR TYPE LFA1-LIFNR,
       NAME1 TYPE LFA1-NAME1,
       LAND1 TYPE LFA1-LAND1,
       TELF1 TYPE LFA1-TELF1,
       END OF ITAB.

   DATA V1 TYPE LFA1-LIFNR.
   SELECT-OPTIONS VENDOR FOR V1 OBLIGATORY.

  START-OF-SELECTION.

    SELECT LIFNR NAME1 LAND1 TELF1
    INTO ITAB
    FROM LFA1
    WHERE LIFNR IN VENDOR.

  WRITE:ITAB-LIFNR COLOR 3,
             25 ITAB-NAME1 COLOR 3,
             70 ITAB-LAND1 COLOR 5,
             90 ITAB-TELF1 COLOR 6.
  ENDSELECT.
  IF SY-SUBRC NE 0.
    MESSAGE 'DATA NOT FOUND' TYPE 'S'.
    ENDIF.
