
REPORT Z_SELECTWOENDSELECT.
TYPES: BEGIN OF TYPE1,
       EBELN TYPE EKKO-EBELN,
       AEDAT TYPE EKKO-AEDAT,
       BSART TYPE EKKO-BSART,
       STATU TYPE EKKO-STATU,
       BUKRS  TYPE EKKO-BUKRS,
       LIFNR TYPE  EKKO-LIFNR,
       END OF TYPE1.
       DATA: ITAB TYPE TABLE OF TYPE1 ,
             WA TYPE TYPE1 .
       DATA V1 TYPE EKKO-AEDAT.
       SELECT-OPTIONS VENDOR FOR V1 OBLIGATORY.
       START-OF-SELECTION.
       SELECT EBELN AEDAT BSART STATU  BUKRS LIFNR INTO TABLE ITAB FROM EKKO
         WHERE EBELN IN VENDOR.
        IF SY-SUBRC NE 0 .
           MESSAGE 'DATA NOT FOUND'  TYPE 'S'.
        ELSE.
          LOOP AT ITAB INTO WA.
            WRITE:/ WA-EBELN , WA-AEDAT , WA-BSART , WA-STATU , WA-BUKRS , WA-LIFNR.
            ENDLOOP.
            ENDIF.
