
REPORT Z_SELECTWITHENDSELECT.
DATA : BEGIN OF ITAB,
       MATNR TYPE MARA-MATNR,
       MTART TYPE MARA-MTART,
       MATKL TYPE MARA-MATKL,
       MEINS TYPE MARA-MEINS,
       END OF ITAB.

       DATA V1 TYPE MARA-MATNR.
       SELECT-OPTIONS MATERIAL FOR V1 OBLIGATORY.

       START-OF-SELECTION.
       SELECT MATNR MTART MATKL MEINS INTO ITAB FROM MARA
         WHERE MATNR IN MATERIAL.
         WRITE:/ ITAB-MATNR COLOR 2,
                20 ITAB-MTART COLOR 3,
                40 ITAB-MATKL COLOR 4,
                60 ITAB-MEINS COLOR 5.
         ENDSELECT.
       IF SY-SUBRC NE 0.
         MESSAGE 'DATA NO FOUND' TYPE 'S'.

       ENDIF.
