PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABSTRIP 'TSTRIPP'
  MODULE TSTRIPP_ACTIVE_TAB_SET.
  CALL SUBSCREEN:
       0101_SCA INCLUDING G_TSTRIPP-PROG '0101',
       0102_SCA INCLUDING G_TSTRIPP-PROG '0102'.
* MODULE STATUS_0100.
*
PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABSTRIP 'TSTRIPP'
  CALL SUBSCREEN:
       0101_SCA,
       0102_SCA.
  MODULE TSTRIPP_ACTIVE_TAB_GET.
 MODULE USER_COMMAND_0100.
