PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABSTRIP 'TSTRIP'
  MODULE TSTRIP_ACTIVE_TAB_SET.
  CALL SUBSCREEN:
       0202_SCA INCLUDING G_TSTRIP-PROG '0202',
       0203_SCA INCLUDING G_TSTRIP-PROG '0203'.
* MODULE STATUS_0201.
*
PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABSTRIP 'TSTRIP'
  CALL SUBSCREEN:
       0202_SCA,
       0203_SCA.
  MODULE TSTRIP_ACTIVE_TAB_GET.
MODULE USER_COMMAND_0201.
