
*
REPORT ZFOODORDERRPRG.
DATA: VCUSTNAME TYPE ZFOODORDERR-CUSTNAME,
      VDISHNAME TYPE ZFOODORDERR-DISHNAME,
      VQUANTITY TYPE ZFOODORDERR-QUANTITY,
      VPRICE TYPE ZFOODORDERR-PRICE,
      VCREATEDON TYPE ZFOODORDERR-CREATEDON,
      VCREATEDAT TYPE ZFOODORDERR-CREATEDAT.
PARAMETERS SALESID TYPE ZFOODORDERR-SALESID .
CALL FUNCTION 'ZFOODORDERFM'
  EXPORTING
    FM_SALESID         = SALESID
 IMPORTING
   FM_CUSTNAME        = VCUSTNAME
   FM_DISHNAME        = VDISHNAME
   FM_QUANTITY        = VQUANTITY
   FM_PRICE           = VPRICE
   FM_CREATEDON       = VCREATEDON
   FM_CREATEDAT       = VCREATEDAT
 EXCEPTIONS
   NOTFOUND           = 1
   OTHERS             = 2.
CASE SY-SUBRC.
   WHEN 0.
     PERFORM SUBR_OUTPUT.
   WHEN 1.
     MESSAGE 'CUSTOMER SALES DATA NOT FOUND' TYPE 'A'.
   WHEN 2.
     MESSAGE 'TRY AGAIN' TYPE 'S'.
ENDCASE.
FORM SUBR_OUTPUT.
  WRITE:/5 'CUSTOMER SALES ID', SALESID COLOR 3.
  WRITE:/5 'CUSTOMER NAME', VCUSTNAME COLOR 5,
        /5 'DISH NAME', VDISHNAME COLOR 5,
        /5 'QUANTITY', VQUANTITY COLOR 5,
        /5 'PRICE', VPRICE COLOR 5,
        /5 'CREATED ON DATE', VCREATEDON COLOR 5,
        /5 'CREATED ON TIME', VCREATEDAT COLOR 5.
ENDFORM.
