FUNCTION ZFOODORDERFM.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(FM_SALESID) TYPE  ZFOODORDERR-SALESID
*"  EXPORTING
*"     REFERENCE(FM_CUSTNAME) TYPE  ZFOODORDERR-CUSTNAME
*"     REFERENCE(FM_DISHNAME) TYPE  ZFOODORDERR-DISHNAME
*"     REFERENCE(FM_QUANTITY) TYPE  ZFOODORDERR-QUANTITY
*"     REFERENCE(FM_PRICE) TYPE  ZFOODORDERR-PRICE
*"     REFERENCE(FM_CREATEDON) TYPE  ZFOODORDERR-CREATEDON
*"     REFERENCE(FM_CREATEDAT) TYPE  ZFOODORDERR-CREATEDAT
*"     REFERENCE(S)
*"  EXCEPTIONS
*"      NOTFOUND
*"----------------------------------------------------------------------
TYPES: BEGIN OF TYPE1,
       CUSTNAME TYPE ZFOODORDERR-CUSTNAME,
       DISHNAME TYPE ZFOODORDERR-DISHNAME,
       QUANTITY TYPE ZFOODORDERR-QUANTITY,
       PRICE    TYPE ZFOODORDERR-PRICE,
       CREATEDON TYPE ZFOODORDERR-CREATEDON,
       CREATEDAT TYPE ZFOODORDERR-CREATEDAT,
       END OF TYPE1.
DATA: ITAB TYPE TYPE1.
SELECT CUSTNAME DISHNAME QUANTITY PRICE CREATEDON CREATEDAT
     INTO ITAB FROM ZFOODORDERR WHERE SALESID EQ FM_SALESID.
ENDSELECT.
IF SY-SUBRC EQ 0.
  FM_CUSTNAME = ITAB-CUSTNAME.
  FM_DISHNAME = ITAB-DISHNAME.
  FM_QUANTITY = ITAB-QUANTITY.
  FM_PRICE = ITAB-PRICE.
  FM_CREATEDON = ITAB-CREATEDON.
  FM_CREATEDAT = ITAB-CREATEDAT.
ELSE.
  RAISE NOTFOUND.
ENDIF.
ENDFUNCTION.
