FUNCTION ZFUNCMODD.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(FM_LIFNR) TYPE  LFA1-LIFNR
*"  EXPORTING
*"     REFERENCE(FM_NAME1) TYPE  LFA1-NAME1
*"     REFERENCE(FM_PSTLZ) TYPE  LFA1-PSTLZ
*"     REFERENCE(FM_LAND1) TYPE  LFA1-LAND1
*"     REFERENCE(FM_TELF1) TYPE  LFA1-TELF1
*"     REFERENCE(FM_ORT01) TYPE  LFA1-ORT01
*"  EXCEPTIONS
*"      NOTFOUND
*"----------------------------------------------------------------------



TYPES : BEGIN OF TYPE1,
        NAME1 TYPE LFA1-NAME1,
        PSTLZ TYPE LFA1-PSTLZ,
        LAND1 TYPE LFA1-LAND1,
        TELF1 TYPE LFA1-TELF1,
        ORT01 TYPE LFA1-ORT01,
        END OF TYPE1.
  DATA: ITAB TYPE TYPE1.

  SELECT NAME1 PSTLZ LAND1 TELF1 ORT01 INTO ITAB FROM LFA1 WHERE LIFNR EQ FM_LIFNR .
    ENDSELECT.
    IF SY-SUBRC EQ 0.
       FM_NAME1 = ITAB-NAME1.
       FM_PSTLZ = ITAB-PSTLZ.
       FM_LAND1 = ITAB-LAND1.
       FM_TELF1 = ITAB-TELF1.
       FM_ORT01 = ITAB-ORT01.
    ELSE.
      RAISE NOTFOUND .
     ENDIF.
ENDFUNCTION.
